snowflakedb/snowpark-java-scala

- scripts/jenkins_regress.sh
> SNOW-767160 Migrate Test Coverage Report to the New Server

- src/test/scala/com/snowflake/snowpark_test/ResultSchemaSuite.scala
> SNOW-825905 Clean Up Legacy Result Schema Tests.

- src/test/scala/com/snowflake/snowpark/ResultAttributesSuite.scala
> SNOW-825905 Remove Other Useless Show Result Schema Tests

- fips-pom.xml
- pom.xml
> SNOW-831999 Upgrade JDBC to Fix GCP IO Issues

- src/test/scala/com/snowflake/snowpark/TestUtils.scala
SNOW-836283 Enhance TestUtils.checkResult to output difference for assert failure.
Fixes #NNNN
> SNOW-836283 Enhance TestUtils.checkResult to output difference for assert failure.

- src/main/scala/com/snowflake/snowpark/internal/ParameterUtils.scala
- src/test/scala/com/snowflake/snowpark/ParameterSuite.scala
> SNOW-838143 Support PKCS#8 RSA Private Key

- fips-pom.xml
- pom.xml
- src/main/scala/com/snowflake/snowpark/internal/ServerConnection.scala
- src/test/scala/com/snowflake/snowpark/APIInternalSuite.scala
- src/test/scala/com/snowflake/snowpark/ParameterSuite.scala
> SNOW-867390 update jdbc version

- fips-pom.xml
- java_doc.xml
- pom.xml
- scripts/jenkins_regress.sh
- sonar-project.properties
- src/main/scala/com/snowflake/snowpark/internal/Utils.scala
> SNOW-867392 Update Version to 1.10.0-snapshot

- .github/repo_meta.yaml
> SNOW-929687 Update Repo Meta

- src/test/scala/com/snowflake/snowpark_test/ComplexDataFrameSuite.scala
> SNOW-946379 Fix Test: Combination of multiple operators with filters

- fips-pom.xml
- pom.xml
- scripts/jenkins_regress.sh
- src/main/java/com/snowflake/snowpark_java/Functions.java
- src/main/scala/com/snowflake/snowpark/functions.scala
- src/test/java/com/snowflake/snowpark_test/JavaFunctionSuite.java
> SNOW-923322 Upgrade to Scala 2.12.18

- LICENSE.txt
- pom.xml
> SNOW-970028 Update license info in POM

- fips-pom.xml
- pom.xml
> SNOW-989128 Upgrade JDBC to 3.14.4

- .github/workflows/precommit-udf-multiple-jdk.yml
- src/main/scala/com/snowflake/snowpark/internal/UDXRegistrationHandler.scala
> SNOW-991842 Support UDTF with Java 17

- .github/workflows/precommit-udf-multiple-jdk.yml
- src/main/scala/com/snowflake/snowpark/internal/UDXRegistrationHandler.scala
SNOW-1012646 Support Java 17 when Registering SP
Fixes #NNNN
> SNOW-1012646 Support Java 17 when Registering SP

- fips-pom.xml
- java_doc.xml
- pom.xml
- src/main/scala/com/snowflake/snowpark/internal/Utils.scala
> SNOW-1063074 Update Version to 1.12.0-SNAPSHOT

- src/main/scala/com/snowflake/snowpark/functions.scala
Fixes [SCT-10614](https://snowflakecomputing.atlassian.net/browse/SCT-10614)
*Adding a new examples for the split function*
[SCT-10614]: https://snowflakecomputing.atlassian.net/browse/SCT-10614?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Added examples for the split function

- src/test/scala/com/snowflake/snowpark/SNTestBase.scala
- src/test/scala/com/snowflake/snowpark_test/ResultSchemaSuite.scala
> SNOW-1180341 Temporarily Disable Objec Type Test for the Incoming Behavior Change

- .github/repo_meta.yaml
> SNOW-1254531: Update repo_meta.yaml

- src/main/java/com/snowflake/snowpark_java/Functions.java
- src/main/scala/com/snowflake/snowpark/functions.scala
- src/test/java/com/snowflake/snowpark_test/JavaFunctionSuite.java
- src/test/scala/com/snowflake/snowpark_test/FunctionSuite.scala
Fixes # [SCT-2681](https://snowflakecomputing.atlassian.net/browse/SCT-2681)
Added com.snowflake.snowpark.functions.countDistinct, it is an alias of count_distinct function.
[SCT-2681]: https://snowflakecomputing.atlassian.net/browse/SCT-2681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add com.snowflake.snowpark.functions.countDistinct

- fips-pom.xml
- java_doc.xml
- pom.xml
- src/main/scala/com/snowflake/snowpark/internal/Utils.scala
> SNOW-1348487 Upgrade version to 1.14.0-SNAPSHOT

- src/test/java/com/snowflake/snowpark_test/JavaRowSuite.java
- src/test/java/com/snowflake/snowpark_test/TestBase.java
- src/test/scala/com/snowflake/snowpark/APIInternalSuite.scala
- src/test/scala/com/snowflake/snowpark/SNTestBase.scala
- src/test/scala/com/snowflake/snowpark_test/DataTypeSuite.scala
> SNOW-1348487 Fix Tests on Preprod

- src/main/java/com/snowflake/snowpark_java/types/SnowflakeFile.java
Fixes SNOW-1369263
Update comments
> SNOW-1369263: Fixing documentation on SnowflakeFile.

- src/main/java/com/snowflake/snowpark_java/types/SnowflakeFile.java
- src/main/scala/com/snowflake/snowpark/types/Variant.scala
- src/test/scala/com/snowflake/snowpark_test/DataTypeSuite.scala
> SNOW-1320314 Reformat Code of Recent PRs

- src/main/java/com/snowflake/snowpark_java/types/CloudProviderToken.java
- src/main/java/com/snowflake/snowpark_java/types/SnowflakeSecrets.java
This PR serves as stubs to which the user's code links while the real implementation is provided by 
https://github.com/snowflakedb/snowflake/pull/194967
> SNOW-658339: Implement CLOUD_PROVIDER_TOKEN secret type for Java

- fips-pom.xml
- pom.xml
> SNOW-1548630 Upgrade JDBC to Support LOB

- src/test/java/com/snowflake/snowpark_test/JavaRowSuite.java
- src/test/java/com/snowflake/snowpark_test/TestBase.java
- src/test/scala/com/snowflake/snowpark/APIInternalSuite.scala
- src/test/scala/com/snowflake/snowpark/SNTestBase.scala
- src/test/scala/com/snowflake/snowpark/TestMethod.java
- src/test/scala/com/snowflake/snowpark_test/DataTypeSuite.scala
1. set parameters at session level.
2. disable all structured type related tests on preprod until those parameters are enabled by default.
> SNOW-1529469 Fix Structured Types related Tests

- src/test/java/com/snowflake/snowpark_test/TestBase.java
- src/test/java/com/snowflake/snowpark_test/TestMethod.java
> SNOW-1599877 Move TestMethod Class to Java Test Dir

- src/main/java/com/snowflake/snowpark_java/Functions.java
- src/main/scala/com/snowflake/snowpark/functions.scala
- src/test/java/com/snowflake/snowpark_test/JavaFunctionSuite.java
- src/test/scala/com/snowflake/snowpark_test/FunctionSuite.scala
Fixes #SNOW-802269
Add below missing functions in scala and java modules
| API | Description |
|--------|--------|
| functions.expr | alias for sqlExpr |
| functions.array | alias for array_construct |
| functions.date_format | alias for to_varchar |
| functions.last | LAST_VALUE | 
> SNOW-802269 - Add missing scala and java functions

- fips-pom.xml
- java_doc.xml
- pom.xml
- src/main/scala/com/snowflake/snowpark/internal/Utils.scala
> SNOW-1567722 Upgrade Version to 1.15.0-SNAPSHOT

- .github/workflows/precommit copy.yml
- .github/workflows/precommit-fips.yml
- build.sbt
> SNOW-1663768 Enable FIPS Tests

- .github/workflows/precommit-fips.yml
- .github/workflows/precommit-multiple-jdk.yml
> SNOW-1663769 Add Multiple JDK Test

- scripts/jenkins_fips_regress_aws.sh
- scripts/jenkins_fips_regress_az.sh
- scripts/jenkins_fips_regress_gcp.sh
- scripts/jenkins_perf.sh
- scripts/jenkins_regress.sh
- scripts/jenkins_regress_az.sh
- scripts/jenkins_regress_az_latest_jdbc.sh
- scripts/jenkins_regress_gcp.sh
- scripts/jenkins_regress_gcp_latest_jdbc.sh
- scripts/jenkins_regress_latest_jdbc.sh
> SNOW-1663770 Jenkins Tests

- .github/workflows/precommit-java-doc-validation.yml
- build.sbt
- java_doc.xml
- scripts/generateJavaDoc.sh
> SNOW-1663771 Enable Doc Generation

- fips-pom.xml
- pom.xml
> SNOW-1826532 Fix Security Vulnerability

- fips-pom.xml
- java_doc.xml
- pom.xml
- src/main/scala/com/snowflake/snowpark/internal/Utils.scala
SNOW-1787485 Bump Up Version to 1.16.0-SNAPSHOT
> SNOW-1787485 Bump Up Version to 1.16.0-SNAPSHOT

- src/test/scala/com/snowflake/snowpark_test/DataFrameSuite.scala
SNOW-1877900 Fix Flatten Function Tests
> SNOW-1877900 Fix Flatten Function Tests

- src/test/scala/com/snowflake/snowpark_test/DataFrameAggregateSuite.scala
- src/test/scala/com/snowflake/snowpark_test/DataFrameReaderSuite.scala
SNOW-1877926 Fix Test Result Sorting Issue
Fixes #NNNN
> SNOW-1877926 Fix Test Result Sorting Issue

- .github/workflows/code-format-check.yml
- .github/workflows/precommit.yml
- v2/build.sbt
- v2/src/main/scala/com/snowflake/snowpark/Session.scala
- v2/src/test/scala/com/snowflake/snowpark_test/DummySuite.scala
> SNOW-1947777 Fix SBT in Github Action

- v2/macros/src/main/scala/com/snowflake/snowpark/internal/SrcPositionInfo.scala
- v2/src/main/scala/com/snowflake/snowpark/Column.scala
- v2/src/main/scala/com/snowflake/snowpark/internal/AstFunc.scala
- v2/src/main/scala/com/snowflake/snowpark/internal/AstNode.scala
- v2/src/main/scala/com/snowflake/snowpark/internal/AstUtils.scala
- v2/src/test/scala/com/snowflake/snowpark/AstUtilsSuite.scala
- v2/src/test/scala/com/snowflake/snowpark/CommonTestBase.scala
- v2/src/test/scala/com/snowflake/snowpark/DummySrcPositionImpl.scala
- v2/src/test/scala/com/snowflake/snowpark/SrcPositionInfoSuite.scala
> SNOW-1964840 Implement Src Position

- v2/src/main/scala/com/snowflake/snowpark/Column.scala
- v2/src/test/scala/com/snowflake/snowpark/InternalColumnSuite.scala
Apply(String), Apply(Int), unary_-, unary_!
> SNOW-1974835: Implement Column Function (Part 1)

- v2/src/main/scala/com/snowflake/snowpark/Column.scala
- v2/src/main/scala/com/snowflake/snowpark/internal/AstNode.scala
- v2/src/main/scala/com/snowflake/snowpark/internal/AstUtils.scala
- v2/src/main/scala/com/snowflake/snowpark/internal/ExprNode.scala
- v2/src/main/scala/com/snowflake/snowpark/internal/StmtNode.scala
- v2/src/test/scala/com/snowflake/snowpark/CommonTestBase.scala
> SNOW-1977138 Rename AstNode

- v2/src/main/scala/com/snowflake/snowpark/Column.scala
- v2/src/test/scala/com/snowflake/snowpark/InternalColumnSuite.scala
Functions implemented:
```
===
equal_to
=!=
not_equal
>
gt
<
lt
<=
leq
>=
geq
<=>
equal_null
equal_nan
```
> SNOW-1976336 Implement Column Function Part 2

- v2/src/main/scala/com/snowflake/snowpark/Column.scala
- v2/src/test/scala/com/snowflake/snowpark/InternalColumnSuite.scala
is_null
is_not_null
||
or
&&
and
between
+
plus
-
minus
*
multiply
/
divide
%
mod
> SNOW-1976371 Implement Column Functions Part 3

- v2/build.sbt
- v2/project/plugins.sbt
- v2/src/main/scala/com/snowflake/snowpark/DataFrame.scala
- v2/src/main/scala/com/snowflake/snowpark/internal/AstBatch.scala
- v2/src/main/scala/com/snowflake/snowpark/internal/AstUtils.scala
- v2/src/main/scala/com/snowflake/snowpark/internal/StmtNode.scala
- v2/src/test/scala/com/snowflake/snowpark/AstBatchSuite.scala
- v2/src/test/scala/com/snowflake/snowpark/AstUtilsSuite.scala
- v2/src/test/scala/com/snowflake/snowpark/CommonTestBase.scala
- v2/src/test/scala/com/snowflake/snowpark/InternalDataFrameSuite.scala
- v2/src/test/scala/com/snowflake/snowpark/UnitTestBase.scala
> SNOW-1981642 Implement AST Batch

- v2/src/main/scala/com/snowflake/snowpark/Column.scala
- v2/src/main/scala/com/snowflake/snowpark/internal/AstUtils.scala
- v2/src/main/scala/com/snowflake/snowpark/internal/ExprNode.scala
- v2/src/main/scala/com/snowflake/snowpark/internal/NameIndices.scala
- v2/src/test/scala/com/snowflake/snowpark/AstBatchSuite.scala
- v2/src/test/scala/com/snowflake/snowpark/AstUtilsSuite.scala
- v2/src/test/scala/com/snowflake/snowpark/CommonTestBase.scala
- v2/src/test/scala/com/snowflake/snowpark/InternalColumnSuite.scala
> SNOW-1990090 Implement Name Indices in Column

- v2/src/main/scala/com/snowflake/snowpark/Column.scala
- v2/src/main/scala/com/snowflake/snowpark/types/DataType.scala
- v2/src/main/scala/com/snowflake/snowpark/types/Geography.scala
- v2/src/main/scala/com/snowflake/snowpark/types/Geometry.scala
- v2/src/main/scala/com/snowflake/snowpark/types/StructType.scala
- v2/src/main/scala/com/snowflake/snowpark/types/Variant.scala
- v2/src/test/scala/com/snowflake/snowpark/InternalDataTypeSuite.scala
Add a Snowpark type to protobuf type converter
> SNOW-1989531 Implement DataTypes

- src/main/scala/com/snowflake/snowpark/internal/analyzer/SnowflakePlan.scala
- src/test/scala/com/snowflake/snowpark_test/DataFrameSetOperationsSuite.scala
> SNOW-880510 Enable Creating View from Union Result

- scripts/profile_az.properties.gpg
> Update Test Profile

- scripts/jenkins_regress.sh
> SNOW-2217467 Disable Sample Data Tests from AWS Preprod Deployments

- src/test/scala/com/snowflake/snowpark_test/TableFunctionSuite.scala
> SNOW-2226926 Fix Result Order Issue in Table Tests

- src/main/java/com/snowflake/snowpark_java/DataFrame.java
- src/main/scala/com/snowflake/snowpark/DataFrame.scala
- src/test/java/com/snowflake/snowpark_test/JavaDataFrameSuite.java
- src/test/scala/com/snowflake/snowpark/TestData.scala
- src/test/scala/com/snowflake/snowpark_test/DataFrameSuite.scala
[SNOW-2287665](https://snowflakecomputing.atlassian.net/browse/SNOW-2287665)
The isEmpty function checks if the DataFrame has any rows by calling first().isEmpty and returning true if no row is found.
[SNOW-2287665]: https://snowflakecomputing.atlassian.net/browse/SNOW-2287665?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SNOW-2287665: Add support for DataFrame.isEmpty

- scripts/deploy-fips.sh
- scripts/utils.sh
Fixes SNOW-2339275
Adding FIPS BouncyCastle libraries needed for test set up to work.
> SNOW-2339275: fix FIPS tests

- build.sbt
Fixes SNOW-2346738
Include sources JAR when publishing to Maven to fulfill requirements: https://central.sonatype.org/publish/requirements/
> SNOW-2346738: resolve sonaUpload validation failure caused by missing sources jar
