src/main/java/com/snowflake/snowpark_java/Functions.java, src/main/scala/com/snowflake/snowpark/functions.scala, src/test/java/com/snowflake/snowpark_test/JavaFunctionSuite.java, src/test/scala/com/snowflake/snowpark_test/FunctionSuite.scala
=> SNOW-897574 Support regexp_replace function

src/test/scala/com/snowflake/snowpark_test/DataFrameSuite.scala
SNOW-929833 Exclude Approx Quantile test from SP
disable Approx Quantile related test from Stored Procs regression test.
=> SNOW-929833 Exclude Approx Quantile test from SP

src/main/java/com/snowflake/snowpark_java/DataFrame.java, src/main/java/com/snowflake/snowpark_java/Session.java, src/main/java/com/snowflake/snowpark_java/TableFunction.java, src/main/java/com/snowflake/snowpark_java/TableFunctions.java, src/main/scala/com/snowflake/snowpark/DataFrame.scala, src/main/scala/com/snowflake/snowpark/Session.scala, src/main/scala/com/snowflake/snowpark/TableFunction.scala, src/main/scala/com/snowflake/snowpark/internal/ErrorMessage.scala, src/main/scala/com/snowflake/snowpark/internal/Utils.scala, src/main/scala/com/snowflake/snowpark/tableFunctions.scala, src/test/java/com/snowflake/snowpark_test/JavaTableFunctionSuite.java, src/test/java/com/snowflake/snowpark_test/JavaUDTFSuite.java, src/test/scala/com/snowflake/code_verification/JavaScalaAPISuite.scala, src/test/scala/com/snowflake/snowpark/ErrorMessageSuite.scala, src/test/scala/com/snowflake/snowpark_test/TableFunctionSuite.scala, src/test/scala/com/snowflake/snowpark_test/UDTFSuite.scala
Support arguments in table functions.
Only Support
```scala
df.join(flatten, json_parse(df("col")))
```
Also Support
```scala
df.join(flatten(json_parse(df("col"))))
```
=> SNOW-966339 Support Arguments in TableFunctions

src/main/scala/com/snowflake/snowpark/DataFrame.scala, src/main/scala/com/snowflake/snowpark/internal/ErrorMessage.scala, src/test/java/com/snowflake/snowpark_test/JavaUDTFSuite.java, src/test/scala/com/snowflake/snowpark/ErrorMessageSuite.scala, src/test/scala/com/snowflake/snowpark_test/TableFunctionSuite.scala
SNOW-966358 Support TableFunction in DataFrame Select()
- `DataFrame.join(<TableFunction>)` renamed columns in source dataframe if the name conflicts with the table function result columns' name.
- Support `DataFrame.select(<TableFunction>)`
=> SNOW-966358 Support TableFunction in DataFrame Select()

src/main/scala/com/snowflake/snowpark/internal/UDFClassPath.scala, src/test/scala/com/snowflake/snowpark/UDFClasspathSuite.scala, src/test/scala/com/snowflake/snowpark/UDFRegistrationSuite.scala
=> SNOW-974909 Remove Usage of ParseUtil

src/main/java/com/snowflake/snowpark_java/SessionBuilder.java, src/main/scala/com/snowflake/snowpark/Session.scala, src/test/java/com/snowflake/snowpark_test/JavaSessionSuite.java, src/test/scala/com/snowflake/snowpark_test/SessionSuite.scala
Fixes: [SCT-7633](https://snowflakecomputing.atlassian.net/browse/SCT-7633)
I just added com.snowflake.snowpark.Session.SessionBuilder.GetOrCreate method for both Scala and Java API to automize getOrCreate method conversion.
[SCT-7633]: https://snowflakecomputing.atlassian.net/browse/SCT-7633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCT-7633 Adding com.snowflake.snowpark.Session.SessionBuilder.getOrCreate

src/main/java/com/snowflake/snowpark_java/TableFunctions.java, src/main/scala/com/snowflake/snowpark/DataFrame.scala, src/main/scala/com/snowflake/snowpark/Session.scala, src/main/scala/com/snowflake/snowpark/internal/ErrorMessage.scala, src/main/scala/com/snowflake/snowpark/tableFunctions.scala, src/test/java/com/snowflake/snowpark_test/JavaSessionSuite.java, src/test/java/com/snowflake/snowpark_test/JavaTableFunctionSuite.java, src/test/scala/com/snowflake/snowpark/ErrorMessageSuite.scala, src/test/scala/com/snowflake/snowpark_test/TableFunctionSuite.scala
- Support `explode` function
- it is a client side table function
- works with `DataFrame.select`, `DataFrame.join` and `Session.tableFunction`
=> SNOW-966360 Support Explode Function

src/test/scala/com/snowflake/snowpark_test/AsyncJobSuite.scala
Fixes #NNNN
I'd like to ad integration testing for async stored proc child jobs now that we support them. For that we need to make this small change to be able to create such test.
=> SNOW-954959: Don't create newSession when running test in SP

src/main/java/com/snowflake/snowpark_java/Column.java, src/main/scala/com/snowflake/snowpark/Column.scala, src/test/java/com/snowflake/snowpark_test/JavaColumnSuite.java, src/test/scala/com/snowflake/snowpark_test/ColumnSuite.scala
Fixes: [SCT-7635](https://snowflakecomputing.atlassian.net/browse/SCT-7635)
In ApacheSpark the function is called isNull because in Scala the snake_case notation is not the standard one. By generating this wrapper both sides are going to have the same name(SparkApache and Snowpark API)
[SCT-7635]: https://snowflakecomputing.atlassian.net/browse/SCT-7635?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCT-7635 Create a wrapper for the is_null function.

.github/workflows/precommit-udf-multiple-jdk.yml, fips-pom.xml, pom.xml, src/main/scala/com/snowflake/snowpark/internal/UDXRegistrationHandler.scala, src/test/scala/com/snowflake/snowpark_test/UDFSuite.scala
=> SNOW-946574 Support Java 17 when Register UDF

src/main/java/com/snowflake/snowpark_java/DataFrame.java, src/main/scala/com/snowflake/snowpark/Column.scala, src/main/scala/com/snowflake/snowpark/DataFrame.scala, src/main/scala/com/snowflake/snowpark/internal/ErrorMessage.scala, src/main/scala/com/snowflake/snowpark/internal/Utils.scala, src/main/scala/com/snowflake/snowpark/internal/analyzer/Expression.scala, src/main/scala/com/snowflake/snowpark/internal/analyzer/ExpressionAnalyzer.scala, src/main/scala/com/snowflake/snowpark/internal/analyzer/MultiChildrenNode.scala, src/main/scala/com/snowflake/snowpark/internal/analyzer/SnowflakeCreateTable.scala, src/main/scala/com/snowflake/snowpark/internal/analyzer/SnowflakePlan.scala, src/main/scala/com/snowflake/snowpark/internal/analyzer/SnowflakePlanNode.scala, src/main/scala/com/snowflake/snowpark/internal/analyzer/SqlGenerator.scala, src/main/scala/com/snowflake/snowpark/internal/analyzer/TableDelete.scala, src/main/scala/com/snowflake/snowpark/internal/analyzer/TableUpdate.scala, src/main/scala/com/snowflake/snowpark/internal/analyzer/binaryPlanNodes.scala, src/main/scala/com/snowflake/snowpark/internal/analyzer/unaryExpressions.scala, src/test/scala/com/snowflake/snowpark/ErrorMessageSuite.scala, src/test/scala/com/snowflake/snowpark_test/DataFrameAliasSuite.scala
=> SNOW-821644 add dataframe alias support

.github/workflows/precommit-java-doc-validation.yml, fips-pom.xml, java_doc.xml, pom.xml, scripts/jenkins_regress.sh, sonar-project.properties, src/main/java/com/snowflake/snowpark_java/DataFrame.java, src/main/java/com/snowflake/snowpark_java/DataFrameWriter.java, src/main/scala/com/snowflake/snowpark/internal/ErrorMessage.scala, src/main/scala/com/snowflake/snowpark/internal/Utils.scala, src/main/scala/com/snowflake/snowpark/internal/analyzer/Expression.scala, src/main/scala/com/snowflake/snowpark/internal/analyzer/ExpressionAnalyzer.scala, src/main/scala/com/snowflake/snowpark/internal/analyzer/MultiChildrenNode.scala, src/main/scala/com/snowflake/snowpark/internal/analyzer/SnowflakePlanNode.scala, src/main/scala/com/snowflake/snowpark/internal/analyzer/binaryPlanNodes.scala, src/main/scala/com/snowflake/snowpark/internal/analyzer/unaryExpressions.scala, src/test/scala/com/snowflake/snowpark_test/DataFrameAliasSuite.scala
1. Update version number to `1.11.0-snapshot`
2. Fix fips release test
3. Fix Java Doc Error
4. Add new merge gate to verify Java doc
=> SNOW-946562 Update Version to 1.11.0-snapshot

src/main/java/com/snowflake/snowpark_java/SessionBuilder.java, src/main/scala/com/snowflake/snowpark/Session.scala, src/test/java/com/snowflake/snowpark_test/JavaSessionSuite.java, src/test/scala/com/snowflake/snowpark_test/SessionSuite.scala
This PR is intend to make easier to track Spark migrated workloads.
It assigns the query_tag with the app name after a new session is created.
=> SCT-2668 Add appName method to SessionBuilder to register in query_tag.

src/main/java/com/snowflake/snowpark_java/Functions.java, src/main/scala/com/snowflake/snowpark/functions.scala, src/test/java/com/snowflake/snowpark_test/JavaFunctionSuite.java, src/test/scala/com/snowflake/snowpark_test/FunctionSuite.scala
Fixes # [SCT-2665](https://snowflakecomputing.atlassian.net/browse/SCT-2665)
Added an overload for the sum function which supports a string parameter.
[SCT-2665]: https://snowflakecomputing.atlassian.net/browse/SCT-2665?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Create an overload for com.snowflake.snowpark.functions.sum

fips-pom.xml, java_doc.xml, pom.xml, src/main/scala/com/snowflake/snowpark/internal/Utils.scala
=> SNOW-1270057 Update Version Number to 1.13.0-SNAPSHOT

src/main/java/com/snowflake/snowpark_java/Functions.java, src/main/scala/com/snowflake/snowpark/functions.scala, src/test/java/com/snowflake/snowpark_test/JavaFunctionSuite.java, src/test/scala/com/snowflake/snowpark_test/FunctionSuite.scala
Fixes [SCT-10981](https://snowflakecomputing.atlassian.net/browse/SCT-10981)
It adds an overload method that receives a column name as parameter for the following functions:
- `com.snowflake.snowpark.functions.max`
- `com.snowflake.snowpark.functions.min`
- `com.snowflake.snowpark.functions.mean`
[SCT-10981]: https://snowflakecomputing.atlassian.net/browse/SCT-10981?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCT-10981 Add an overload method for functions.max, functions.min and functions.mean

src/test/scala/com/snowflake/snowpark/UDFInternalSuite.scala
=> SNOW-1227362 Re-enable Package Related Tests

src/main/scala/com/snowflake/snowpark/DataFrame.scala, src/main/scala/com/snowflake/snowpark/internal/analyzer/ExpressionAnalyzer.scala, src/main/scala/com/snowflake/snowpark/internal/analyzer/SnowflakePlanNode.scala, src/main/scala/com/snowflake/snowpark/internal/analyzer/SqlGenerator.scala, src/test/scala/com/snowflake/snowpark_test/DataFrameAliasSuite.scala, src/test/scala/com/snowflake/snowpark_test/DataFrameSuite.scala
Fixed two errors
1. df alias doesn't work in the JOIN condition, for example `df1.alias("a").join(df2.alias("b"), col("a.col") === col("b.col"))`
2. df alias requires child's output, but the child's SnowflakePlan can be empty.
=> SNOW-1335123 Fix DF Alias in the JOIN Condition

src/test/java/com/snowflake/snowpark_test/JavaSessionNonStoredProcSuite.java, src/test/java/com/snowflake/snowpark_test/JavaSessionSuite.java
Test `appName` can't be executed from Sproc because it accesses the local file system.
Moved it to `JavaSessionNonStoredProcSuite`, which will be not executed in the Sproc tests.
=> SNOW-1348487 Fix Test Failure of SessionSuite in Sproc

.pre-commit-config.yaml, src/main/scala/com/snowflake/snowpark/types/Variant.scala, src/test/scala/com/snowflake/snowpark_test/DataTypeSuite.scala
=> SNOW-1320314: fix Null handling in Variants

src/test/scala/com/snowflake/snowpark_test/UDTFSuite.scala
SNOW-1468615 Fix Result Order Issue in the UDTF Suite
Result order of UDTF has changed in the recent Snowflake result. This PR enables sort in `checkResult` function in UDTF suite to fix this issue.
=> SNOW-1468615 Fix Result Order Issue in the UDTF Suite

src/main/java/com/snowflake/snowpark_java/SessionBuilder.java, src/main/scala/com/snowflake/snowpark/Session.scala, src/test/java/com/snowflake/snowpark_test/JavaSessionNonStoredProcSuite.java, src/test/scala/com/snowflake/snowpark_test/SessionSuite.scala
Fixes [SIT-1627](https://snowflakecomputing.atlassian.net/browse/SIT-1627)
When a new session is created, the app name will be set to the session query tag in JSON format instead of the key=value format used in previous versions. The goal of this change is to make the app name compatible with the `updateQueryTag` function.
[SIT-1627]: https://snowflakecomputing.atlassian.net/browse/SIT-1627?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SIT-1627: Set the app name in the session query tag in JSON format

src/main/scala/com/snowflake/snowpark/CopyableDataFrame.scala, src/main/scala/com/snowflake/snowpark/MergeBuilder.scala, src/main/scala/com/snowflake/snowpark/Updatable.scala, src/main/scala/com/snowflake/snowpark/internal/OpenTelemetry.scala, src/test/java/com/snowflake/snowpark_test/JavaOpenTelemetrySuite.java, src/test/scala/com/snowflake/snowpark/OpenTelemetryEnabled.scala, src/test/scala/com/snowflake/snowpark_test/OpenTelemetrySuite.scala
1. Collect Span Info from Copyable and Updatable Dataframes
2. Improve the test function to automatically detect line numbers
3. Add Java offset to action functions
=> SNOW-1480775 Collect Span Info from Copyable and Updatable Dataframes

src/main/java/com/snowflake/snowpark_java/types/CloudProviderToken.java, src/main/java/com/snowflake/snowpark_java/types/SnowflakeSecrets.java, src/main/scala/com/snowflake/snowpark/CopyableDataFrame.scala, src/main/scala/com/snowflake/snowpark/DataFrame.scala, src/main/scala/com/snowflake/snowpark/DataFrameNaFunctions.scala, src/main/scala/com/snowflake/snowpark/DataFrameReader.scala, src/main/scala/com/snowflake/snowpark/DataFrameStatFunctions.scala, src/main/scala/com/snowflake/snowpark/DataFrameWriter.scala, src/main/scala/com/snowflake/snowpark/MergeBuilder.scala, src/main/scala/com/snowflake/snowpark/RelationalGroupedDataFrame.scala, src/main/scala/com/snowflake/snowpark/Updatable.scala, src/main/scala/com/snowflake/snowpark/internal/OpenTelemetry.scala, src/test/java/com/snowflake/snowpark_test/JavaOpenTelemetryEnabled.java, src/test/java/com/snowflake/snowpark_test/JavaOpenTelemetrySuite.java, src/test/scala/com/snowflake/code_verification/JavaScalaAPISuite.scala, src/test/scala/com/snowflake/snowpark/APIInternalSuite.scala, src/test/scala/com/snowflake/snowpark/MethodChainSuite.scala, src/test/scala/com/snowflake/snowpark_test/OpenTelemetrySuite.scala
Implement Method Chain in the Open Telemetry
=> SNOW-1480779 Support Method Chain in the Telemetry

src/test/scala/com/snowflake/snowpark_test/DataFrameSuite.scala
SNOW-1480787 Fix DataFrameSuite test to validate with pivot v1 and pivot v2
Fixes #SNOW-1480787
Run the df.stat.crosstab with pivot v1 and pivot v2 enabled (via ENABLE_PIVOT_VIEW_WITH_OBJECT_AGG parameter)
The test is updated to match the python tests as well.
=> SNOW-1480787 Fix DataFrameSuite test to validate with pivot v1 and pivot v2

src/main/scala/com/snowflake/snowpark/Updatable.scala, src/test/java/com/snowflake/snowpark_test/JavaUpdatableSuite.java, src/test/scala/com/snowflake/snowpark/SNTestBase.scala, src/test/scala/com/snowflake/snowpark_test/UpdatableSuite.scala
=> SNOW-1551862 Don't Report Error in UpdateResult when ERROR_ON_NONDETERMINISTIC_UPDATE=true

src/main/java/com/snowflake/snowpark_java/Functions.java, src/main/scala/com/snowflake/snowpark/functions.scala, src/test/java/com/snowflake/snowpark_test/JavaFunctionSuite.java, src/test/scala/com/snowflake/snowpark_test/FunctionSuite.scala
Fixes #802269
Add log10 and log1p functions for scala and java which takes column name as both ColumnType and StringType
| API | Description |
|--------|--------|
| function.log10 | Computes the logarithm of the given column in base 10 |
| functions.log1p | Computes the natural logarithm of the given value plus one |
| functions.base64 | Computes the BASE64 encoding of a column and returns it as a string column.|
| functions.unbase64 | Decodes a BASE64 encoded string column and returns it as a column. |
(For …
=> Snow 802269 add log10, log1p, base64 and unbase64 functions

src/main/java/com/snowflake/snowpark_java/Functions.java, src/main/scala/com/snowflake/snowpark/functions.scala, src/test/java/com/snowflake/snowpark_test/JavaFunctionSuite.java, src/test/scala/com/snowflake/snowpark_test/FunctionSuite.scala
Fixes #802269
Add locate, randn  and ntile functions for scala and java which takes column name as both ColumnType and StringType
| API | Description |
|--------|--------|
| functions.locate | Locate the position of the first occurrence of substr in a string column |
| functions.ntile | NTILE |
| funstions.randn | Generate Random number | 
=> Snow 802269 add locate, randn and ntile functions

src/main/scala/com/snowflake/snowpark/internal/OpenTelemetry.scala, src/test/scala/com/snowflake/snowpark_test/OpenTelemetrySuite.scala
=> SNOW-1638551 Only Emit Span Once in the Nested Actions

src/main/java/com/snowflake/snowpark_java/Functions.java, src/main/scala/com/snowflake/snowpark/functions.scala, src/test/java/com/snowflake/snowpark_test/JavaFunctionSuite.java, src/test/scala/com/snowflake/snowpark_test/FunctionSuite.scala
Fixes [SIT-2192](https://snowflakecomputing.atlassian.net/browse/SIT-2192)
It adds a new overload for the function `com.snowflake.snowpark.functions.round` that allows to indicate the scale as an integer value. Also, it improves the code documentation for the other overloads of this function.
[SIT-2192]: https://snowflakecomputing.atlassian.net/browse/SIT-2192?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SIT-2192 Add a new overload for `com.snowflake.snowpark.functions.round` function

src/main/scala/com/snowflake/snowpark/internal/OpenTelemetry.scala, src/test/scala/com/snowflake/snowpark_test/OpenTelemetrySuite.scala
=> SNOW-1638551 Start Open Telemetry Span before Process Actions

src/main/java/com/snowflake/snowpark_java/Row.java, src/main/java/com/snowflake/snowpark_java/types/StructType.java, src/main/scala/com/snowflake/snowpark/Row.scala, src/main/scala/com/snowflake/snowpark/internal/ServerConnection.scala, src/main/scala/com/snowflake/snowpark/types/StructType.scala, src/test/java/com/snowflake/snowpark_test/JavaRowSuite.java, src/test/scala/com/snowflake/snowpark_test/RowSuite.scala
Adds an implementation for the `Row.getAs(String)` for retreving values from a `Row` using field name.
Fixes [SIT-2214](https://snowflakecomputing.atlassian.net/browse/SIT-2214)
[SIT-2214]: https://snowflakecomputing.atlassian.net/browse/SIT-2214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SIT-2214] Add support for `com.snowflake.snowpark.Row.getAs(String)`

src/main/java/com/snowflake/snowpark_java/Session.java, src/main/scala/com/snowflake/snowpark/Session.scala, src/main/scala/com/snowflake/snowpark/internal/ErrorMessage.scala, src/main/scala/com/snowflake/snowpark/internal/ServerConnection.scala, src/main/scala/com/snowflake/snowpark/internal/analyzer/SnowflakePlan.scala, src/test/java/com/snowflake/snowpark_test/JavaSessionSuite.java, src/test/scala/com/snowflake/snowpark/ErrorMessageSuite.scala, src/test/scala/com/snowflake/snowpark/ServerConnectionSuite.scala, src/test/scala/com/snowflake/snowpark_test/SqlSuite.scala
SNOW-1022196 Support binding parameters for snowpark java api
=> SNOW-1022196 Support binding parameters for snowpark java api

src/main/java/com/snowflake/snowpark_java/Session.java, src/main/scala/com/snowflake/snowpark/Session.scala
We found a regression in the release tests. It is a legacy issue, Java Sproc can invoke Scala session. However, when Java code invokes Scala functions, the default value of function arguments will be ignored. Therefore, the new change in the `Session.sql` will break all existing code related this function.
This PR refactor the `Session.sql` function to split it to two functions, with and without parameters. Then the new API will not impact any existing code.
=> SNOW-1820719 Refactor Session.sql Function

src/main/scala/com/snowflake/snowpark/internal/Utils.scala, src/test/scala/com/snowflake/snowpark/UtilsSuite.scala
SNOW-1793953
Fixes #183 
This allows stage paths starting with `/` and will not try to prepend `@` to them for the native apps use case. This mirrors the same change in snowpark-python ([PR](https://github.com/snowflakedb/snowpark-python/pull/2889)), and also applies the same change for `snow://` paths which is already implemented in snowpark-python ([PR](https://github.com/snowflakedb/snowpark-python/pull/1346)).
=> SNOW-1793953 allow GET from relative paths starting with / for native apps

src/main/scala/com/snowflake/snowpark/MergeClause.scala
[SNOW-2098807](https://snowflakecomputing.atlassian.net/browse/SNOW-2098807)
`assignments.keys.toSeq` produces the incorrect order of keys in the `Map`. Converting the `Map` to a sequence first maintains the order of insertion. 
[SNOW-2098807]: https://snowflakecomputing.atlassian.net/browse/SNOW-2098807?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SNOW-2098807: Correct NotMatchedClauseBuilder Insert column mapping

scripts/jenkins_fips_regress_aws.sh, scripts/jenkins_fips_regress_az.sh, scripts/jenkins_fips_regress_gcp.sh, scripts/jenkins_regress.sh, scripts/jenkins_regress_az.sh, scripts/jenkins_regress_az_latest_jdbc.sh, scripts/jenkins_regress_gcp.sh, scripts/jenkins_regress_gcp_latest_jdbc.sh, scripts/jenkins_regress_latest_jdbc.sh
SNOW-2273045
Needed to wrap the related parameters inside quotes for `sbt` to pick up on the filter flag with the `testOnly` command together.
=> SNOW-2273045: use quotes to actually filter out SampleDataTest

build.sbt, project/build.properties, scripts/deploy.sh, src/main/scala/com/snowflake/snowpark/internal/Utils.scala
SNOW-2282231
Follow the example of https://github.com/snowflakedb/spark-snowflake/pull/617/files to update the `deploy.sh` script to use new Maven Central repository publishing process.
Includes additional necessary changes to `sbt` version as well as `sbt` plugin versions.
Currently publishing still requires a manual step of logging into the central repository to manually publish the artifacts after verification. This can be automated later.
Additionally, this PR changes the client package name to include the Scala version as a suffix (e.g. `snowpark_2.13`​) to follow the design for [server-side UDxF and SProc support](https://docs.google.com/document/d/1z8yfSw7Q_PHav2OQen9bZJ5iJnRB3qaAtQR73BiyN6U/edit?tab=t.0#heading=h.p8ilppt5ftg).
=> SNOW-2282231: Update build and release scripts for Maven

src/main/java/com/snowflake/snowpark_java/DataFrame.java, src/main/scala/com/snowflake/snowpark/DataFrame.scala, src/test/java/com/snowflake/snowpark_test/JavaDataFrameSuite.java, src/test/scala/com/snowflake/snowpark_test/DataFrameSuite.scala
Fixes [SNOW-2246204](https://snowflakecomputing.atlassian.net/browse/SNOW-2246204)
It adds a new overload for the `com.snowflake.snowpark.DataFrame.sort` function:
- `sort(String, String*)`
[SNOW-2246204]: https://snowflakecomputing.atlassian.net/browse/SNOW-2246204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SNOW-2246204 Add new overload for `DataFrame.sort`

src/main/java/com/snowflake/snowpark_java/Functions.java, src/main/scala/com/snowflake/snowpark/functions.scala, src/test/java/com/snowflake/snowpark_test/JavaFunctionSuite.java, src/test/scala/com/snowflake/snowpark_test/FunctionSuite.scala
Fixes [SNOW-2246264](https://snowflakecomputing.atlassian.net/browse/SNOW-2246264)
It adds new overloads for the `com.snowflake.snowpark.functions.lpad` and `com.snowflake.snowpark.functions.rpad` functions:
* `lpad(Column, Int, String)`
* `lpad(Column, Int, Array[Byte])`
* `rpad(Column, Int, String)`
* `rpad(Column, Int, Array[Byte])`
[SNOW-2246264]: https://snowflakecomputing.atlassian.net/browse/SNOW-2246264?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SNOW-2246264 Add new overloads for `functions.lpad` and `functions.rpad`

src/main/java/com/snowflake/snowpark_java/CaseExpr.java, src/main/java/com/snowflake/snowpark_java/Functions.java, src/main/scala/com/snowflake/snowpark/Column.scala, src/main/scala/com/snowflake/snowpark/functions.scala, src/test/java/com/snowflake/snowpark_test/JavaColumnSuite.java, src/test/scala/com/snowflake/snowpark_test/ColumnSuite.scala
Fixes 
[SNOW-2246196](https://snowflakecomputing.atlassian.net/browse/SNOW-2246196)
[SNOW-2245985](https://snowflakecomputing.atlassian.net/browse/SNOW-2245985)
This pull request enhances the usability of the `when` and `otherwise` methods in both the Java and Scala APIs for Snowpark by allowing them to accept any literal value (such as `String`, `int`, `boolean`, or `null`) in addition to `Column` objects. The changes also update documentation and add comprehensive tests to cover these new use cases.
**API Enhancements:**
* The `when` and `otherwise` methods in …
=> SNOW-2246196 | SNOW-2245985 Adding support for 'when'  and 'otherwise'  methods when Any value type

build.sbt, scripts/deploy-common.sh
Fixes SNOW-2346738
Validation of packages to be release failed due to naming of fat test JAR containing compiled test sources and dependencies. See
- https://es-ci-legacy-mainvalidation-001.jenkinsdev1.us-west-2.aws-dev.app.snowflake.com/job/MavenPushThunderSnowClient/47/console
- https://snowflake.slack.com/archives/C054J469AN4/p1758170003398679?thread_ts=1758085517.918489&cid=C054J469AN4
We resolve this issue by changing the SBT artifact publishing commands to now do the following.
- When publishing locally via`sbt +publishLocal`​ or `sbt +publishLocalSigned`​, …
=> SNOW-2346738: resolve sonaUpload validation failure caused by fat test jar name
